# NumPy

In [2]:
pip install numpy

In [1]:
import numpy as np

In [5]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a.shape

(3, 5)

In [7]:
a.ndim

2

In [9]:
a.dtype.name

'int32'

In [10]:
a.itemsize

4

In [11]:
a.size

15

In [12]:
type(a)

numpy.ndarray

In [13]:
b= np.array([6,7,8])
b

array([6, 7, 8])

In [14]:
b.shape

(3,)

## Array Creation

In [22]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [23]:
a.dtype

dtype('int32')

In [30]:
b= np.array([1.2,3.5,5.1])
b.dtype

dtype('float64')

In [32]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,3,4), dtype=np.int16)